### PR TITLE
Update debian package sections

### PR DESCRIPTION
**Pull request by ahresse**
This is intended to fix `lintian` messages about `wrong-section-according-to-package-name`.

@IsaacJT for review

### CODE REVIEW

**Comment by IsaacJT** [comment]
Thanks @ahresse! We will look at the best way to apply all of these changes internally and then publish them on GitHub.

**Comment by ahresse** [comment]
I also propose to set section of cmocka-extentions to devel to be consitent with cmocka debian package:  https://salsa.debian.org/debian/cmocka/-/blame/debian/1.1.7-3/debian/control?ref_type=tags#L2

**Comment by gehwolf** [comment]
@ahresse  we applied your changes to `debian.native` on the main branch. With the latest release for debian we published it for the `debian/main`.  
Please have a look if you miss something otherwise we can close this as merged.

**Comment by ahresse** [comment]
https://github.com/Elektrobit/cmocka_extensions/pull/2/commits/fb82b533b80b2387223f543b5d789d6279046469 merged as https://github.com/Elektrobit/cmocka_extensions/commit/3f114c60c99188db4598bb369229b813f3cbd289

Remains https://github.com/Elektrobit/cmocka_extensions/pull/2/commits/8ee081366ce8c323f7d5b11cb87a04ec143c6d1a that should also be merged to be consistent with cmocka debian package: (https://salsa.debian.org/debian/cmocka/-/blame/debian/1.1.7-3/debian/control?ref_type=tags#L2)

**Comment by ahresse** [comment]
Closing.

Remaining commit here: https://github.com/Elektrobit/cmocka_extensions/pull/8

**Pull request closed without merging**
