### PR TITLE
Use debian/clean file for deletions

### PR DESCRIPTION
**Pull request by ahresse**
This is mostly a question of style but I find this way cleaner with the advantage to be data driven rather than using hard command lines.

### CODE REVIEW

**Comment by ahresse** [comment]
@IsaacJT + @gehwolf for review.

**Comment by gehwolf** [comment]
Thanks looks good from our side , we will integrate it first into main/debian.native and release it here on debian/main with the upcoming release.

**Comment by gehwolf** [comment]
@ahresse  we applied your changes to `debian.native` on the main branch. With the latest release for debian we published it for the `debian/main`.  
Please have a look if you miss something otherwise we can close this as merged.

**Comment by ahresse** [comment]
Merged as: https://github.com/Elektrobit/cmocka_extensions/commit/73b9857f02063c93239d15e4f94d3b580edad8b3

Closing.

**Pull request closed without merging**
